// Code generated by generate_multi_flags.py; DO NOT EDIT.

package cli

// []bool

func BoolsVar(register Register, p *[]bool, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newBoolValues(p), opts))
}

func Bools(register Register, name string, options ...FlagOptionApplyer) *[]bool {
	p := new([]bool)
	_ = BoolsVar(register, p, name, options...)
	return p
}

// []uint8

func Uint8sVar(register Register, p *[]uint8, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newUint8Values(p), opts))
}

func Uint8s(register Register, name string, options ...FlagOptionApplyer) *[]uint8 {
	p := new([]uint8)
	_ = Uint8sVar(register, p, name, options...)
	return p
}

// []uint16

func Uint16sVar(register Register, p *[]uint16, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newUint16Values(p), opts))
}

func Uint16s(register Register, name string, options ...FlagOptionApplyer) *[]uint16 {
	p := new([]uint16)
	_ = Uint16sVar(register, p, name, options...)
	return p
}

// []uint32

func Uint32sVar(register Register, p *[]uint32, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newUint32Values(p), opts))
}

func Uint32s(register Register, name string, options ...FlagOptionApplyer) *[]uint32 {
	p := new([]uint32)
	_ = Uint32sVar(register, p, name, options...)
	return p
}

// []uint64

func Uint64sVar(register Register, p *[]uint64, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newUint64Values(p), opts))
}

func Uint64s(register Register, name string, options ...FlagOptionApplyer) *[]uint64 {
	p := new([]uint64)
	_ = Uint64sVar(register, p, name, options...)
	return p
}

// []int8

func Int8sVar(register Register, p *[]int8, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newInt8Values(p), opts))
}

func Int8s(register Register, name string, options ...FlagOptionApplyer) *[]int8 {
	p := new([]int8)
	_ = Int8sVar(register, p, name, options...)
	return p
}

// []int16

func Int16sVar(register Register, p *[]int16, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newInt16Values(p), opts))
}

func Int16s(register Register, name string, options ...FlagOptionApplyer) *[]int16 {
	p := new([]int16)
	_ = Int16sVar(register, p, name, options...)
	return p
}

// []int32

func Int32sVar(register Register, p *[]int32, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newInt32Values(p), opts))
}

func Int32s(register Register, name string, options ...FlagOptionApplyer) *[]int32 {
	p := new([]int32)
	_ = Int32sVar(register, p, name, options...)
	return p
}

// []int64

func Int64sVar(register Register, p *[]int64, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newInt64Values(p), opts))
}

func Int64s(register Register, name string, options ...FlagOptionApplyer) *[]int64 {
	p := new([]int64)
	_ = Int64sVar(register, p, name, options...)
	return p
}

// []float32

func Float32sVar(register Register, p *[]float32, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newFloat32Values(p), opts))
}

func Float32s(register Register, name string, options ...FlagOptionApplyer) *[]float32 {
	p := new([]float32)
	_ = Float32sVar(register, p, name, options...)
	return p
}

// []float64

func Float64sVar(register Register, p *[]float64, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newFloat64Values(p), opts))
}

func Float64s(register Register, name string, options ...FlagOptionApplyer) *[]float64 {
	p := new([]float64)
	_ = Float64sVar(register, p, name, options...)
	return p
}

// []string

func StringsVar(register Register, p *[]string, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newStringValues(p), opts))
}

func Strings(register Register, name string, options ...FlagOptionApplyer) *[]string {
	p := new([]string)
	_ = StringsVar(register, p, name, options...)
	return p
}

// []int

func IntsVar(register Register, p *[]int, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newIntValues(p), opts))
}

func Ints(register Register, name string, options ...FlagOptionApplyer) *[]int {
	p := new([]int)
	_ = IntsVar(register, p, name, options...)
	return p
}

// []uint

func UintsVar(register Register, p *[]uint, name string, options ...FlagOptionApplyer) error {
	var opts FlagOptions
	opts.applyName(name)
	opts.applyFlagOptions(options)

	return register.RegisterFlag(newFlag(newUintValues(p), opts))
}

func Uints(register Register, name string, options ...FlagOptionApplyer) *[]uint {
	p := new([]uint)
	_ = UintsVar(register, p, name, options...)
	return p
}
