// Code generated by generate_flags.py; DO NOT EDIT.

package cli

import (
	"time"
)

// bool

func BoolVar(register Register, p *bool, name string, options ...FlagOptionApplyer) error {
	return Var(register, newBoolValue(p), name, options...)
}

func Bool(register Register, name string, options ...FlagOptionApplyer) *bool {
	p := new(bool)
	_ = BoolVar(register, p, name, options...)
	return p
}

// uint8

func Uint8Var(register Register, p *uint8, name string, options ...FlagOptionApplyer) error {
	return Var(register, newUint8Value(p), name, options...)
}

func Uint8(register Register, name string, options ...FlagOptionApplyer) *uint8 {
	p := new(uint8)
	_ = Uint8Var(register, p, name, options...)
	return p
}

// uint16

func Uint16Var(register Register, p *uint16, name string, options ...FlagOptionApplyer) error {
	return Var(register, newUint16Value(p), name, options...)
}

func Uint16(register Register, name string, options ...FlagOptionApplyer) *uint16 {
	p := new(uint16)
	_ = Uint16Var(register, p, name, options...)
	return p
}

// uint32

func Uint32Var(register Register, p *uint32, name string, options ...FlagOptionApplyer) error {
	return Var(register, newUint32Value(p), name, options...)
}

func Uint32(register Register, name string, options ...FlagOptionApplyer) *uint32 {
	p := new(uint32)
	_ = Uint32Var(register, p, name, options...)
	return p
}

// uint64

func Uint64Var(register Register, p *uint64, name string, options ...FlagOptionApplyer) error {
	return Var(register, newUint64Value(p), name, options...)
}

func Uint64(register Register, name string, options ...FlagOptionApplyer) *uint64 {
	p := new(uint64)
	_ = Uint64Var(register, p, name, options...)
	return p
}

// int8

func Int8Var(register Register, p *int8, name string, options ...FlagOptionApplyer) error {
	return Var(register, newInt8Value(p), name, options...)
}

func Int8(register Register, name string, options ...FlagOptionApplyer) *int8 {
	p := new(int8)
	_ = Int8Var(register, p, name, options...)
	return p
}

// int16

func Int16Var(register Register, p *int16, name string, options ...FlagOptionApplyer) error {
	return Var(register, newInt16Value(p), name, options...)
}

func Int16(register Register, name string, options ...FlagOptionApplyer) *int16 {
	p := new(int16)
	_ = Int16Var(register, p, name, options...)
	return p
}

// int32

func Int32Var(register Register, p *int32, name string, options ...FlagOptionApplyer) error {
	return Var(register, newInt32Value(p), name, options...)
}

func Int32(register Register, name string, options ...FlagOptionApplyer) *int32 {
	p := new(int32)
	_ = Int32Var(register, p, name, options...)
	return p
}

// int64

func Int64Var(register Register, p *int64, name string, options ...FlagOptionApplyer) error {
	return Var(register, newInt64Value(p), name, options...)
}

func Int64(register Register, name string, options ...FlagOptionApplyer) *int64 {
	p := new(int64)
	_ = Int64Var(register, p, name, options...)
	return p
}

// float32

func Float32Var(register Register, p *float32, name string, options ...FlagOptionApplyer) error {
	return Var(register, newFloat32Value(p), name, options...)
}

func Float32(register Register, name string, options ...FlagOptionApplyer) *float32 {
	p := new(float32)
	_ = Float32Var(register, p, name, options...)
	return p
}

// float64

func Float64Var(register Register, p *float64, name string, options ...FlagOptionApplyer) error {
	return Var(register, newFloat64Value(p), name, options...)
}

func Float64(register Register, name string, options ...FlagOptionApplyer) *float64 {
	p := new(float64)
	_ = Float64Var(register, p, name, options...)
	return p
}

// string

func StringVar(register Register, p *string, name string, options ...FlagOptionApplyer) error {
	return Var(register, newStringValue(p), name, options...)
}

func String(register Register, name string, options ...FlagOptionApplyer) *string {
	p := new(string)
	_ = StringVar(register, p, name, options...)
	return p
}

// int

func IntVar(register Register, p *int, name string, options ...FlagOptionApplyer) error {
	return Var(register, newIntValue(p), name, options...)
}

func Int(register Register, name string, options ...FlagOptionApplyer) *int {
	p := new(int)
	_ = IntVar(register, p, name, options...)
	return p
}

// uint

func UintVar(register Register, p *uint, name string, options ...FlagOptionApplyer) error {
	return Var(register, newUintValue(p), name, options...)
}

func Uint(register Register, name string, options ...FlagOptionApplyer) *uint {
	p := new(uint)
	_ = UintVar(register, p, name, options...)
	return p
}

// time.Duration

func DurationVar(register Register, p *time.Duration, name string, options ...FlagOptionApplyer) error {
	return Var(register, newDurationValue(p), name, options...)
}

func Duration(register Register, name string, options ...FlagOptionApplyer) *time.Duration {
	p := new(time.Duration)
	_ = DurationVar(register, p, name, options...)
	return p
}
