#!/usr/bin/env python

from gotypes import types, imports

res = "// Code generated by generate_rest.py; DO NOT EDIT.\n"
res += "\n"
res += "package cli\n"
res += "\n"
res += "import (\n"
for pkg in imports:
    res += "\t\"%s\"\n" % pkg
res += ")\n"

for (typ, name, _) in types:
    res += "\n"
    res += "// []%s\n" % typ
    res += "\n"
    res += "func Rest%ssVar(register Register, p *[]%s, name string, options ...RestOptionApplyer) error {\n" % (name, typ)
    res += "\treturn RestVar(register, new%sValues(p), name, options...)\n" % name
    res += "}\n"
    res += "\n"
    res += "func Rest%ss(register Register, name string, options ...RestOptionApplyer) *[]%s {\n" % (name, typ)
    res += "\tp := new([]%s)\n" % typ
    res += "\t_ = Rest%ssVar(register, p, name, options...)\n" % name
    res += "\treturn p\n"
    res += "}\n"

with open("./rest_gen.go", "w") as f:
    f.write(res)
