#!/usr/bin/env python

from gotypes import types, imports

res = "// Code generated by generate_multi_flags.py; DO NOT EDIT.\n"
res += "\n"
res += "package cli\n"
res += "\n"
res += "import (\n"
for pkg in imports:
    res += "\t\"%s\"\n" % pkg
res += ")\n"

for (typ, name, _) in types:
    res += "\n"
    res += "// []%s\n" % typ
    res += "\n"
    res += "func %ssVar(register Register, p *[]%s, name string, options ...FlagOptionApplyer) error {\n" % (name, typ)
    res += "\treturn Var(register, new%sValues(p), name, options...)\n" % name
    res += "}\n"
    res += "\n"
    res += "func %ss(register Register, name string, options ...FlagOptionApplyer) *[]%s {\n" % (name, typ)
    res += "\tp := new([]%s)\n" % typ
    res += "\t_ = %ssVar(register, p, name, options...)\n" % name
    res += "\treturn p\n"
    res += "}\n"

with open("./flags_multi_gen.go", "w") as f:
    f.write(res)
