#!/usr/bin/env python

from gotypes import types, imports

res = "// Code generated by generate_args.py; DO NOT EDIT.\n"
res += "\n"
res += "package cli\n"
res += "\n"
res += "import (\n"
for pkg in imports:
    res += "\t\"%s\"\n" % pkg
res += ")\n"

for (typ, name, _) in types:
    res += "\n"
    res += "// %s\n" % typ
    res += "\n"
    res += "func %sArgVar(register Register, p *%s, name string, options ...ArgOptionApplyer) error {\n" % (name, typ)
    res += "\treturn ArgVar(register, new%sValue(p), name, options...)\n" % name
    res += "}\n"
    res += "\n"
    res += "func %sArg(register Register, name string, options ...ArgOptionApplyer) *%s {\n" % (name, typ)
    res += "\tp := new(%s)\n" % typ
    res += "\t_ = %sArgVar(register, p, name, options...)\n" % name
    res += "\treturn p\n"
    res += "}\n"

with open("./args_gen.go", "w") as f:
    f.write(res)
