#!/usr/bin/env python

flags = [
    ("bool", "Bool"),
    ("uint8", "Uint8"),
    ("uint16", "Uint16"),
    ("uint32", "Uint32"),
    ("uint64", "Uint64"),
    ("int8", "Int8"),
    ("int16", "Int16"),
    ("int32", "Int32"),
    ("int64", "Int64"),
    ("float32", "Float32"),
    ("float64", "Float64"),
    ("string", "String"),
    ("int", "Int"),
    ("uint", "Uint"),
    # TODO: Duration
    # TODO: Func
]

res = "// Code generated by generate_flags.py; DO NOT EDIT.\n"
res += "\n"
res += "package cli\n"

for (typ, name) in flags:
    res += "\n"
    res += "// %s\n" % (typ)
    res += "\n"
    res += "func %sVar(register Register, p *%s, name string, options ...FlagOptionApplyer) error {\n" % (name, typ)
    res += "\tvar opts FlagOptions\n"
    res += "\topts.applyName(name)\n"
    res += "\topts.applyFlagOptions(options)\n"
    res += "\n"
    res += "\treturn register.RegisterFlag(newFlag(new%sValue(p), opts))\n" % name
    res += "}\n"
    res += "\n"
    res += "func %s(register Register, name string, options ...FlagOptionApplyer) *%s {\n" % (name, typ)
    res += "\tp := new(%s)\n" % typ
    res += "\t_ = %sVar(register, p, name, options...)\n" % name
    res += "\treturn p\n"
    res += "}\n"

with open("./flags_gen.go", "w") as f:
    f.write(res)
