#!/usr/bin/env python

from gotypes import types

res = "// Code generated by generate_flags.py; DO NOT EDIT.\n"
res += "\n"
res += "package cli\n"

for (typ, name, _) in types:
    res += "\n"
    res += "// %s\n" % typ
    res += "\n"
    res += "func %sVar(register Register, p *%s, name string, options ...FlagOptionApplyer) error {\n" % (name, typ)
    res += "\tvar opts FlagOptions\n"
    res += "\topts.applyName(name)\n"
    res += "\topts.applyFlagOptions(options)\n"
    res += "\n"
    res += "\treturn register.RegisterFlag(newFlag(new%sValue(p), opts))\n" % name
    res += "}\n"
    res += "\n"
    res += "func %s(register Register, name string, options ...FlagOptionApplyer) *%s {\n" % (name, typ)
    res += "\tp := new(%s)\n" % typ
    res += "\t_ = %sVar(register, p, name, options...)\n" % name
    res += "\treturn p\n"
    res += "}\n"

with open("./flags_gen.go", "w") as f:
    f.write(res)
