// Code generated by generate_rest.py; DO NOT EDIT.

package cli

// []bool

func RestBoolsVar(register Register, p *[]bool, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newBoolValues(p), opts))
}

func RestBools(register Register, name string, options ...RestOptionApplyer) *[]bool {
	p := new([]bool)
	_ = RestBoolsVar(register, p, name, options...)
	return p
}

// []uint8

func RestUint8sVar(register Register, p *[]uint8, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newUint8Values(p), opts))
}

func RestUint8s(register Register, name string, options ...RestOptionApplyer) *[]uint8 {
	p := new([]uint8)
	_ = RestUint8sVar(register, p, name, options...)
	return p
}

// []uint16

func RestUint16sVar(register Register, p *[]uint16, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newUint16Values(p), opts))
}

func RestUint16s(register Register, name string, options ...RestOptionApplyer) *[]uint16 {
	p := new([]uint16)
	_ = RestUint16sVar(register, p, name, options...)
	return p
}

// []uint32

func RestUint32sVar(register Register, p *[]uint32, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newUint32Values(p), opts))
}

func RestUint32s(register Register, name string, options ...RestOptionApplyer) *[]uint32 {
	p := new([]uint32)
	_ = RestUint32sVar(register, p, name, options...)
	return p
}

// []uint64

func RestUint64sVar(register Register, p *[]uint64, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newUint64Values(p), opts))
}

func RestUint64s(register Register, name string, options ...RestOptionApplyer) *[]uint64 {
	p := new([]uint64)
	_ = RestUint64sVar(register, p, name, options...)
	return p
}

// []int8

func RestInt8sVar(register Register, p *[]int8, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newInt8Values(p), opts))
}

func RestInt8s(register Register, name string, options ...RestOptionApplyer) *[]int8 {
	p := new([]int8)
	_ = RestInt8sVar(register, p, name, options...)
	return p
}

// []int16

func RestInt16sVar(register Register, p *[]int16, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newInt16Values(p), opts))
}

func RestInt16s(register Register, name string, options ...RestOptionApplyer) *[]int16 {
	p := new([]int16)
	_ = RestInt16sVar(register, p, name, options...)
	return p
}

// []int32

func RestInt32sVar(register Register, p *[]int32, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newInt32Values(p), opts))
}

func RestInt32s(register Register, name string, options ...RestOptionApplyer) *[]int32 {
	p := new([]int32)
	_ = RestInt32sVar(register, p, name, options...)
	return p
}

// []int64

func RestInt64sVar(register Register, p *[]int64, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newInt64Values(p), opts))
}

func RestInt64s(register Register, name string, options ...RestOptionApplyer) *[]int64 {
	p := new([]int64)
	_ = RestInt64sVar(register, p, name, options...)
	return p
}

// []float32

func RestFloat32sVar(register Register, p *[]float32, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newFloat32Values(p), opts))
}

func RestFloat32s(register Register, name string, options ...RestOptionApplyer) *[]float32 {
	p := new([]float32)
	_ = RestFloat32sVar(register, p, name, options...)
	return p
}

// []float64

func RestFloat64sVar(register Register, p *[]float64, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newFloat64Values(p), opts))
}

func RestFloat64s(register Register, name string, options ...RestOptionApplyer) *[]float64 {
	p := new([]float64)
	_ = RestFloat64sVar(register, p, name, options...)
	return p
}

// []string

func RestStringsVar(register Register, p *[]string, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newStringValues(p), opts))
}

func RestStrings(register Register, name string, options ...RestOptionApplyer) *[]string {
	p := new([]string)
	_ = RestStringsVar(register, p, name, options...)
	return p
}

// []int

func RestIntsVar(register Register, p *[]int, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newIntValues(p), opts))
}

func RestInts(register Register, name string, options ...RestOptionApplyer) *[]int {
	p := new([]int)
	_ = RestIntsVar(register, p, name, options...)
	return p
}

// []uint

func RestUintsVar(register Register, p *[]uint, name string, options ...RestOptionApplyer) error {
	var opts RestOptions
	opts.applyName(name)
	opts.applyRestOptions(options)

	return register.RegisterRestArgs(newRest(newUintValues(p), opts))
}

func RestUints(register Register, name string, options ...RestOptionApplyer) *[]uint {
	p := new([]uint)
	_ = RestUintsVar(register, p, name, options...)
	return p
}
