#!/usr/bin/env python

MAX_UINT8 = 255

res = "// Code generated by generate_ansi_style_string.py; DO NOT EDIT.\n"
res += "\n"
res += "package colors\n"
res += "\n"
res += "const ansiStyleString = "

for i in range(MAX_UINT8 + 1):
    if i != 0 and i % 8 == 0:
        res += "\n\t"
    elif i != 0:
        res += " "

    res += '"\\x1b[%sm"' % i

    if i != MAX_UINT8:
        res += " +"

res += "\n"

with open("./colors_ansi_style_string_gen.go", "w") as f:
    f.write(res)
