#!/usr/bin/env python

MAX_UINT8 = 255

res = "// Code generated by generate_ansi_attribute_string.py; DO NOT EDIT.\n"
res += "\n"
res += "package colors\n"
res += "\n"

res += "const ansiAttributeString = "

for i in range(MAX_UINT8 + 1):
    if i != 0 and i % 8 == 0:
        res += "\n\t"
    elif i != 0:
        res += " "

    # TODO(SuperPaintman):
    #     Try it with '"\\x1b[%03dm"'. It might simplify the attributeToString
    #     function.
    #
    #     But maybe some terminals don't support it.
    res += '"\\x1b[%dm"' % i

    if i != MAX_UINT8:
        res += " +"

res += "\n"
res += "\n"

res += "var ansiAttributeIndex = [...]uint16{"

offset = 0
for i in range(MAX_UINT8 + 1):
    if i % 8 == 0:
        res += "\n\t"
    else:
        res += " "

    res += str(offset) + ","

    offset += len("\x1b[%dm" % i)

res += "\n\t" + str(offset) + ","

res += "\n"
res += "}\n"

with open("./colors_ansi_attribute_string_gen.go", "w") as f:
    f.write(res)
