#!/usr/bin/env python

MAX_UINT8 = 255

styles = {
    "bold": (1, "ResetBold"),
    "dim": (2, "ResetDim"),
    "italic": (3, "ResetItalic"),
    "underline": (4, "ResetUnderline"),
    "inverse": (7, "ResetInverse"),
    "hidden": (8, "ResetHidden"),
    "strikethrough": (9, "ResetStrikethrough"),
    "overline": (53, "ResetOverline"),

    "black": (30, "ResetColor"),
    "red": (31, "ResetColor"),
    "green": (32, "ResetColor"),
    "yellow": (33, "ResetColor"),
    "blue": (34, "ResetColor"),
    "magenta": (35, "ResetColor"),
    "cyan": (36, "ResetColor"),
    "white": (37, "ResetColor"),

    "black_bright": (90, "ResetColor"),
    "red_bright": (91, "ResetColor"),
    "green_bright": (92, "ResetColor"),
    "yellow_bright": (93, "ResetColor"),
    "blue_bright": (94, "ResetColor"),
    "magenta_bright": (95, "ResetColor"),
    "cyan_bright": (96, "ResetColor"),
    "white_bright": (97, "ResetColor"),

    "bg_black": (40, "ResetBgColor"),
    "bg_red": (41, "ResetBgColor"),
    "bg_green": (42, "ResetBgColor"),
    "bg_yellow": (43, "ResetBgColor"),
    "bg_blue": (44, "ResetBgColor"),
    "bg_magenta": (45, "ResetBgColor"),
    "bg_cyan": (46, "ResetBgColor"),
    "bg_white": (47, "ResetBgColor"),

    "bg_black_bright": (100, "ResetBgColor"),
    "bg_red_bright": (101, "ResetBgColor"),
    "bg_green_bright": (102, "ResetBgColor"),
    "bg_yellow_bright": (103, "ResetBgColor"),
    "bg_blue_bright": (104, "ResetBgColor"),
    "bg_magenta_bright": (105, "ResetBgColor"),
    "bg_cyan_bright": (106, "ResetBgColor"),
    "bg_white_bright": (107, "ResetBgColor"),
}

reset_styles = ["Reset"] * (MAX_UINT8 + 1)

for _, (style, style_reset) in styles.items():
    reset_styles[style] = style_reset

res = "// Code generated by generate_reset_styles.py; DO NOT EDIT.\n"
res += "\n"
res += "package colors\n"
res += "\n"
res += "var resetStyles = [%d]Style{" % (MAX_UINT8 + 1)

for i, v in enumerate(reset_styles):
    if i % 8 == 0:
        res += "\n\t"
    else:
        res += " "

    res += v + ","

res += "\n"
res += "}\n"

with open("./colors_reset_styles_gen.go", "w") as f:
    f.write(res)
