name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    examples-matrix:
        needs:
            - lint
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.result }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/github-script@v5
              id: set-matrix
              with:
                  script: |
                      const fs = require('fs');
                      const { promisify } = require('util');

                      const readdirAsync = promisify(fs.readdir);

                      const examples = await readdirAsync('./examples');

                      return examples;

    lint-example:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go 1.17
              uses: actions/setup-go@v2
              with:
                  go-version: "1.17"

            - name: Download Go dependencies
              run: go mod download
              working-directory: ./examples/${{ matrix.example }}

            - name: Run Go linters
              uses: golangci/golangci-lint-action@v2
              with:
                  version: v1.42
                  skip-go-installation: true
              working-directory: ./examples/${{ matrix.example }}

    build-example:
        needs:
            - examples-matrix
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    # - macos-latest
                    # - windows-latest
                go:
                    - "1.17"
                    # - "1.16"
                    # - "1.15"
                    # - "1.14"
                    # - "1.13"
                example: ${{ fromJSON(needs.examples-matrix.outputs.matrix) }}
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go ${{ matrix.go }}
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go }}

            - name: Download Go dependencies
              run: go mod download
              working-directory: ./examples/${{ matrix.example }}

            - name: Build an example
              run: go build .
              working-directory: ./examples/${{ matrix.example }}
