name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    build-examples-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.result }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/github-script@v5
              id: set-matrix
              with:
                  script: |
                      const fs = require('fs');
                      const { promisify } = require('util');

                      const readdirAsync = promisify(fs.readdir);

                      const examples = await readdirAsync('./examples');

                      return examples;

    build-examples:
        runs-on: ubuntu-latest
        needs:
            - build-examples-matrix
        strategy:
            matrix:
                example: ${{ fromJSON(needs.build-examples-matrix.outputs.matrix) }}
        steps:
            - run: |
                  echo (${{ matrix.example }})
